### ISSUE TITLE
[Question] Which GPI Pins are used ?

### ISSUE THREAD

**Issue by Noschvie** [FKW9/esp-smartmeter-netznoe#1]
Hello
how have the M-Bus Interface (RX, TX) to be connected to the ESP-WROOM-32 ?
Want use this device : [ESP32 NodeMCU](https://www.az-delivery.de/en/products/esp32-developmentboard)

https://github.com/mitsubishievo99/esp-smartmeter-netznoe/blob/83cd244952b45712161aca232fa0c840dfb842c4/src/main.cpp#L28

Thanks!

**Comment by FKW9** [comment]
@Noschvie RX is not used on the M-Bus Slave.

You have to connect **TX** to **GPIO16**

**Comment by Noschvie** [comment]
Thanks!
