### ISSUE TITLE
Testdaten

### ISSUE THREAD

**Issue by HWHardsoft** [FKW9/esp-smartmeter-netznoe#11]
Hallo,

Ich habe Deinen Code etwas vereinfacht (Display und Wifi entfernt) und mit  der Arduino IDE erfolgreich kompiliert. Ich möchte diesen Code als Beispielcode für die Einbindung von Stromzählern für einen eigenen MBUS Slave Feather Wing verwenden.

Leider komme ich aus Deutschland und bei uns sind die Stromzähler mit RS485 ausgestattet. Deshalb meine Frage. Gibt es irgndwo Testdaten (mit dem dazugehörigen Key) mit denen man die Software testen kann? Oder gar einen Simulator für den Zähler?

LG

Hartmut

![20230815_115252](https://github.com/FKW9/esp-smartmeter-netznoe/assets/3049858/5f772ff3-73c2-4966-9ca8-cc58495728f9)

**Comment by FKW9** [comment]
Folgende Test-Daten kommen vom Sagecom T210-D **von Netz Niederösterreich**
KEY: `825DC0D167DEEB63F49DAB4F31A86CC7`
DATA: `68FAFA6853FF000167DB084B464D675000088181F82000006005C1FA38BCC6D9594E5A7C3659138B7EE99A8347BF50B998F8338581084512A3780CACBF5BCB366744C99E99E53A12E867D4EDE68EF82A91F6D76C086C73AD5754CE8F1313D9F738C850D49362750A9B6FCBE33ADE62A16C62A9B5CAC79331E9786281604BC92422A124E0C3B9C979D0E265DA601403C556B8960944C424BAD49D63ADABFBAEDA075D66882F5CB55A7AAD43FC24470F3B23BD6BBBFF71C6447A3DEB2EA47D8060D7AAF62F149C0DD4CF60FDC91C20ED9A6DCCF06DA54DFB9B5F4560DFB5364E0E01056A07364A605F8575F3841D517D07220614CFC7CF98825EE720C51CBC59166814146853FF1101674CC1D217B8D8034CC7515FE02095610D16`

Folgende Test-Daten kommen vom KaifaMA309 **von Netz Niederösterreich**
KEY: `36C66639E48A8CA4D6BC8B282A793BBB`
DATA: `68FAFA6853FF000167DB084B464D675000000981F8200000002388D5AB4F97515AAFC6B88D2F85DAA7A0E3C0C40D004535C397C9D037AB7DBDA329107615444894A1A0DD7E85F02D496CECD3FF46AF5FB3C9229CFE8F3EE4606AB2E1F409F36AAD2E50900A4396FC6C2E083F373233A69616950758BFC7D63A9E9B6E99E21B2CBC2B934772CA51FD4D69830711CAB1F8CFF25F0A329337CBA51904F0CAED88D61968743C8454BA922EB00038182C22FE316D16F2A9F544D6F75D51A4E92A1C4EF8AB19A2B7FEAA32D0726C0ED80229AE6C0F7621A4209251ACE2B2BC66FF0327A653BB686C756BE033C7A281F1D2A7E1FA31C3983E15F8FD16CC5787E6F517166814146853FF110167419A3CFDA44BE438C96F0E38BF83D98316`

Leider sind die M-Bus Frames auch innerhalb Österreichs Netzbetreiber unterschiedlich, wie z.B. von den Vorarlberger Kraftwerken, was das Dekodieren erschwert. Dies wird in meinem Programm nicht erkannt, gibt aber einen branch dazu, siehe: Issue #10 und Branch [vkw-test](https://github.com/FKW9/esp-smartmeter-netznoe/tree/vkw-test).

Einen Simulator für den uC gibt es hier: https://github.com/FKW9/esp-smartmeter-netznoe/issues/10#issuecomment-1638599180
Simulator für den Zähler kenne ich keinen.

**Comment by HWHardsoft** [comment]
Vielen Dank für die schnelle Hilfe. Beide Testdaten + Codes scheinen bei mir zu funktionieren.

![Ausgabe SagemcomT210-D_Niederösterreich](https://github.com/FKW9/esp-smartmeter-netznoe/assets/3049858/738a1c5d-cc26-4dfc-8964-836ee2d36774)

![AUsgabe KaifaMA209](https://github.com/FKW9/esp-smartmeter-netznoe/assets/3049858/861fc6da-b41f-4558-9701-e147df27b0f8)

Mein Program läuft jetzt auf Featherboards mit ESP32 und RP2040. Getestet habe ich bislang:

- Adafruit Feather HUZZAH32
- Sparkfun ESP32 Thing Plus
- Sparkfun Thing Plus RP2040

Wenn ich es für Boards mit anderen Prozessoren compiliere, bekomme ich immer Probleme mit den MBED Bibliotheken. Deshalb überlege ich, eventuell noch einen anderen Stack für TLS zu verwenden z.B. WolfSSL

Das Programm werde ich die nächsten Tage auf meinen Gihub account  hochladen. Parallel arbeite ich auch noch an einer kleinen Zählerdemo für den gleichen Wing, der dann die Simulation eines Verbrauchszählers via MBUS ermöglicht: 


![20230818_160140](https://github.com/FKW9/esp-smartmeter-netznoe/assets/3049858/363599a2-cec0-4940-ac26-a542c2e0f6d1)

Wie man sieht, bin ich da schon ziemlich weit.

**Comment by HWHardsoft** [comment]
Nachtrag: Ich habe zwischenzeitlich realisiert, dass es [hier](https://github.com/FKW9/esp-smartmeter-netznoe/issues/8) schon eine Implementierung für Arduino ohne die Verwendung von MBEDTLS gibt. In diesem Beispiel wird ausschließlich die Crypto Library für Arduino verwendet. Habe ich mittlerweile auch so in meinem Programm übernommen und funktioniert super. Dadurch ist der Code jetzt auch für andere Prozessoren bzw. Featherboards kompatibel. Erfolgreich getest wurde jetzt:

- Adafruit Feather HUZZAH32
- Sparkfun ESP32 Thing Plus
- Sparkfun Thing Plus RP2040
- Adafruit Feather M0 Express
- Adafruit Feather nRF52840 Express
- Adafruit Feather HUZZAH ESP8266 (läuft aber sinnlos, da nur eine UART vorhanden)
- Arduino MKR WIFI1010
