### ISSUE TITLE
VKW Honeywell DM515 Smartmeter _cos phi nicht Korrekt

### ISSUE THREAD

**Issue by Soundrico** [FKW9/esp-smartmeter-netznoe#12]
änderungen im Code (issue 7)
dennoch anzeige de cosphi 0,000 bzw sporadisch 1,983
Ideen?

**Comment by FKW9** [comment]
Also wenn die M-Bus Daten korrekt empfangen werden und wirklich nur der Wert hin und her springt geh ich mal davon aus das Honeywell vielleicht einen anderen Datentypen verwendet? Kannst du ein rohes, dekodiertes M-Bus Frame schicken?
Also `DEBUG_OUTPUT` Flag auf true dann sollte es geprintet werden

**Comment by Soundrico** [comment]
VOILA:

Encoded raw data stream:
68FAFA6853FF000167DB08454C5310207BB88C8201552100013F8240E27DD024F1BC9BA9CA232CC68C33EDB2A646733C3508B87A8F1CAE7339F52F35673DD1AD2FF798C133E0264F16AAC9D500C1F1DA2A879D7567DDED18D6AE971FFF4841F5D75BEFB2BEEA365461140880D966CC7661B16816A3689F0FA420BF690390B98BF53381EA418C07D79FD74C4F8BC2DE42396A42EECDA55198D1E2C66182874AD3338465AE44F8C946CD4BFD0C2B480A11EA8F498474F7087DFB72BD4C72515A3C9E7423E034FA82209E8E20E7B05276B8E5A081CE8967564637A7FCF1D61F00C0859EEC5C299B2D4CA2AEEBFD7AD140760BF85FB5C3F12C3E25E90D325FD127166872726853FF11016737C91A3FBB2F4E38DC0A149F5FE67861FDB0DC971269C3D9861BC80C42DA3943CBE6589A3138EEA66512C2DB197A96BCA6940BC673AFDFBB76B855D0A7FB06F34499DFED8F2E6A4E0D6FA890E2B0BBE6981BCF2CFE6005CC191C108EB66E990556ED10A68BD4CD37E6902EF72F7A1600
Found OBIS code: 0000010000FF
Unix Time 1697183550
Timestamp 13.10.2023 09:52:30 UTC +02:00
Found OBIS code: 0000600100FF
Found OBIS code: 00002A0000FF
Found OBIS code: 0100200700FF
VoltageL1 229.60
Found OBIS code: 0100340700FF
VoltageL2 230.70
Found OBIS code: 0100480700FF
VoltageL3 231.40
Found OBIS code: 01001F0700FF
CurrentL1 0.61
Found OBIS code: 0100330700FF
CurrentL2 0.93
Found OBIS code: 0100470700FF
CurrentL3 0.23
Found OBIS code: 0100010700FF
ActivePowerPlus 212.00
Found OBIS code: 0100020700FF
ActivePowerMinus 0.00
Found OBIS code: 0100010800FF
ActiveEnergyPlus 320604.00
Found OBIS code: 0100020800FF
ActiveEnergyMinus 0.00
Found OBIS code: 0100030800FF
ReactivePowerPlus 743.00
Found OBIS code: 0100040800FF
ReactivePowerMinus 84075.00
Received valid data!

**Comment by FKW9** [comment]
Sry, falscher Branch... Füge bitte nach Zeile 183 in main.cpp das hinzu:
```
#ifdef DEBUG_OUTPUT
        for (int i = 0; i < payload_length; i++)
        {
            Serial.printf("%02X", plaintext[i]);
        }
#endif
````
Und schick mir diese dekodierten daten

Aber in dem was du geschickt hast, empfängt er garkeinen Leistungsfaktor (Obis Code 1.0.13.7.0.255 bzw. 01000D0700FF).
Was meinst du dann mit "sporadisch" ?

**Comment by FKW9** [comment]
Es könnte aber sogar sein, dass wie im Falle bei Issue #10 (auch VKW) dein Smartmeter gar keinen Leistungsfaktor sendet.

**Comment by Soundrico** [comment]
hallo nochmal
anbei der neue print:

Encoded raw data stream:
68FAFA6853FF000167DB08454C5310207BB88C820155210001CFF96B55328F368631AFE9CC68CD1A2F02CA1FFF57460AA05A57EAC81F047B29CDB71C5294D024ED81218B17EFF4C81105DE949D6282D8067402132262DABB7548E3EAE88FBF8C5939310380415B16A296A2DC18A804E73E98D9A12729901B0568F1801E2A4B8E6B4146C94AFB2F2563D725493808509043960F06EEE984899F4FEE5E1A1F8D5EFD42A45FD909307C5028DE365C3E7642D12F03F9FB2043F4E6395607D811A46A6914CA336C743A16308ECD9AEB2564CDDACBE680649FE9971E49303ED4600094D6411E12D46511CEE52D7866DF5772583622F38088D939717B5CC5E1A47158166872726853FF1101672AF72ECB3AFC17A6DB5E767729D1835065DE5A1630AB67F01A17B9304F7A96EEE7AAF4CCCBA23F16763B8689F71C6E44127336DB9D1A70EE0042F73990351B06E26A692F9DA551CEDD15FCE7296DAD954656A73D7235AC243DDC88D1FF86BD29EFE76547D4E7DFE13728800DB718161D
0F0001CB650C07E70A0F070D0E1900FF8880021009060000010000FF090C07E70A0F070D0E1900FF8880020209060000600100FF090E31454C53303230383130383137320202090600002A0000FF0910454C5331323030323038313038313732020309060100200700FF1208F502020FFF1623020309060100340700FF12090102020FFF1623020309060100480700FF12090002020FFF16230203090601001F0700FF12003B02020FFE1621020309060100330700FF12006502020FFE1621020309060100470700FF12001702020FFE1621020309060100010700FF06000000E602020F00161B020309060100020700FF060000000002020F00161B020309060100010800FF060005692D02020F00161E020309060100020800FF060000000002020F00161E020309060100030800FF060000036502020F001620020309060100040800FF0600016CCE02020F001620Found OBIS code: 0000010000FF
Unix Time 1697368465
Timestamp 15.10.2023 13:14:25 UTC +02:00
Found OBIS code: 0000600100FF
Found OBIS code: 00002A0000FF
Found OBIS code: 0100200700FF
VoltageL1 229.30
Found OBIS code: 0100340700FF
VoltageL2 230.50
Found OBIS code: 0100480700FF
VoltageL3 230.40
Found OBIS code: 01001F0700FF
CurrentL1 0.59
Found OBIS code: 0100330700FF
CurrentL2 1.01
Found OBIS code: 0100470700FF
CurrentL3 0.23
Found OBIS code: 0100010700FF
ActivePowerPlus 230.00
Found OBIS code: 0100020700FF
ActivePowerMinus 0.00
Found OBIS code: 0100010800FF
ActiveEnergyPlus 354605.00
Found OBIS code: 0100020800FF
ActiveEnergyMinus 0.00
Found OBIS code: 0100030800FF
ReactivePowerPlus 869.00
Found OBIS code: 0100040800FF
ReactivePowerMinus 93390.00
Received valid data!

**Comment by FKW9** [comment]
Also anhand deiner Daten würd ich sagen: Dein Smartmeter gibt ganz einfach keinen Leistungsfaktor aus.

**Comment by Soundrico** [comment]
Ok, werde mal bei der vkw nachfragen 


Von meinem iPhone gesendet

**Comment by Soundrico** [comment]
Hallo Florian,

die VKW schickt kein cosphi über den Mbus!

folgende Daten werden an der Kundenschnittstelle übergeben:

{{8,0-0:1.0.0.255,1,0}, Clock, attribute 1 – OBIS code
{8,0-0:1.0.0.255,2,0}, Clock, attribute 2 – time
{1,0-0:96.1.0.255,0,0}, Device ID 1 manufacturing number, attribute 0 – 
OBIS code, serial number
{1,0-0:42.0.0.255,0,0}, COSEM logical device name, attribute 0 – OBIS 
code, logical device number
{3,1-0:32.7.0.255,0,0}, Instantaneous voltage L1, attribute 0 – OBIS 
code, value, scalar and unit
{3,1-0:31.7.0.255,0,0}, Instantaneous current L1, attribute 0 – OBIS 
code, value, scalar and unit
{3,1-0:1.7.0.255,0,0}; Instantaneous active import power (+P), attribute 
0 – OBIS code, value, scalar and unit
{3,1-0:2.7.0.255,0,0}; Instantaneous active export power (-P), attribute 
0 – OBIS code, value, scalar and unit
{3,1-0:1.8.0.255,0,0}, Active energy import (+A), attribute 0 – OBIS 
code, value, scalar and unit
{3,1-0:2.8.0.255,0,0}, Active energy export (-A), attribute 0 – OBIS 
code, value, scalar and unit
{3,1-0:3.8.0.255,0,0}, Rective energy import (+R), attribute 0 – OBIS 
code, value, scalar and unit
{3,1-0:4.8.0.255,0,0} Rective energy export (-R), attribute 0 – OBIS 
code, value, scalar and unit



Die HT/NT Aufteilung der Wirkenergie ist hier nicht enthalten in unserer 
Schnittstellenausprägung.

Eine entsprechende Freischaltung ist nicht vorgesehen.


LG Soundrico


Am 2023-10-16 17:16, schrieb Florian:

**Comment by FKW9** [comment]
Alles klar, danke für die info!
