### ISSUE TITLE
Anpassung an TiNetz

### ISSUE THREAD

**Issue by DaPeace** [FKW9/esp-smartmeter-netznoe#14]
Hallo,
Ich würde deinen Code gerne für meinen TiNetz-Anschluß verwenden.
Ich hab jetzt deinen Code mal für mich angepasst und um MQTT erweitert. Es wird der selbe Kaifa-SM verwendet aber dadurch das sich die Provider-Kennung unterscheidet komme ich da irgendwie nicht weiter.
Ich komme immer bei "Serial.println("Packet was decrypted but data is invalid!");" raus.
Ich hab hier ein Python-Script am laufen bei dem man den Provider einstellen muß.
So schaut da im Script der Code aus:
class Supplier:
    name = None
    frame1_start_bytes_hex = '68fafa68'
    frame1_start_bytes = b'\x68\xfa\xfa\x68'  # 68 FA FA 68
    frame2_end_bytes = b'\x16'
    ic_start_byte = None
    enc_data_start_byte = None

class SupplierTINETZ(Supplier):
    name = "TINETZ"
    frame2_start_bytes_hex = '68727268'
    frame2_start_bytes = b'\x68\x72\x72\x68'  # 68 72 72 68
    ic_start_byte = 23
    enc_data_start_byte = 27

class SupplierEVN(Supplier):
    name = "EVN"
    frame2_start_bytes_hex = '68141468'
    frame2_start_bytes = b'\x68\x14\x14\x68'  # 68 14 14 68
    ic_start_byte = 22
    enc_data_start_byte = 26

Kannst du mir sagen wo ich das anpassen kann bei deinem Code? 
Grüsse und Danke schonmal!!

**Comment by FKW9** [comment]
in [dlms.h](https://github.com/FKW9/esp-smartmeter-netznoe/blob/master/src/dlms.h):
- `DLMS_HEADER1_LENGTH` auf 27
- `DLMS_IC_OFFSET` auf 23

Dann wird die paylaod-length denke ich auch nicht passen...
[https://github.com/FKW9/esp-smartmeter-netznoe/blob/72f538406e99a903e9722aa38984d9a9b3a05c15/src/main.cpp#L153-L154](https://github.com/FKW9/esp-smartmeter-netznoe/blob/72f538406e99a903e9722aa38984d9a9b3a05c15/src/main.cpp#L153-L154)
[](url)

Kannst du mal die rohen, kodierten Daten schicken?

**Comment by DaPeace** [comment]
Hallo FKW, danke schonmal für die Antwort.
[cutout_Tinetz.log](https://github.com/FKW9/esp-smartmeter-netznoe/files/13623295/cutout_Tinetz.log)
[received.log](https://github.com/FKW9/esp-smartmeter-netznoe/files/13623296/received.log)
Anbei mal das was ich über den PC mitgeschnitten habe. cutout_Tinetz müsste eigentlich das sein was einen Block darstellt wenn ich nicht völlig daneben liege. Grüsse, Jan

**Comment by FKW9** [comment]
Dein Datenpaket:
`68FAFA6853FF000167DB084B464D102007051C82015521004347DA9F0408B31EA33C015E5895BA018A54DC386E78E24E29EABD90925C29278A410A550E9C9DE44CD97DAA76E28053BDF90B462369D8EC5A13F06A9618F8BAA95F4B0AC1ACC2F8444F683C64F1D17D0538E309FF7394EAB298A7A8D732884751054831EA24B78F6B30FF120C761405BB26665DFEA59CFD2DEA667B5E46C74680C8C26824CB0988EBB8A3161AF2FDA33999E8AD25E4165C1A15A0F985D11FD767CF766769564AD02CB42E8213E47AFBDEA7578D781B118AF30CD04D3C9B7AF8EA4107AE991C029662279F88489A13912588A1A2CA645B026745C5FE2340BCEF932512A988BB42166872726853FF110167CC1322628FA905C0F12D51F03A3CFC1AA748EDA14F3C740F384A3AAA6BBABB26E56458E5CDE3B45F8C07635D5578870C7E29FD51850AB3219A903EB1B39B6BAC3133988B796BE6EB75005F7637C31D3F6A5FAF721067DE3E4DE354DC75A1C94DF97E5D7D1857F0E6D413B8EB856916`

Passt auch mit dem Format von VKW überein (siehe #10 oder Branch [vkw-test](https://github.com/FKW9/esp-smartmeter-netznoe/tree/vkw-test))

Ändere mal folgende Variablen auf den Wert:
[https://github.com/FKW9/esp-smartmeter-netznoe/blob/b2c20f459761682da1d9b9684755af54f8c2330c/src/main.cpp#L156-L157](https://github.com/FKW9/esp-smartmeter-netznoe/blob/b2c20f459761682da1d9b9684755af54f8c2330c/src/main.cpp#L156-L157)

Und wie oben schon geschrieben in [dlms.h](https://github.com/FKW9/esp-smartmeter-netznoe/blob/master/src/dlms.h):
- `DLMS_HEADER1_LENGTH` auf 27
- `DLMS_IC_OFFSET` auf 23

**Comment by DaPeace** [comment]
Ich hab das jetzt mal genau so angepasst. Jetzt bekomme ich 
"Unsupported OBIS medium" was immerhin schonmal viel mehr ist als das was ich vorher hatte. Kannst du mir evt. sagen was da noch nicht passt?

**Comment by FKW9** [comment]
Der Code vom Branch [vkw-test](https://github.com/FKW9/esp-smartmeter-netznoe/tree/vkw-test) sollte dies lösen. Vergleich beide und implementier die fehlenden Teile!

**Comment by DaPeace** [comment]
Super Sache! Funktioniert mit dem Kaifa-Smartmeter mit dem vkw-branch sofort. Direkt noch um MQTT erweitert und schon läuft es Autonom ohne extra Rechner. Fettes Dankeschön von mir !
