### ISSUE TITLE
Which board to use

### ISSUE THREAD

**Issue by JohannesKaranitsch** [FKW9/esp-smartmeter-netznoe#5]
Is the [M-Bus to Serial Converter](https://www.mikroe.com/m-bus-slave-click) under Requirements section the right board to use?
I thought the meter is the slave and I have to use a master to read it, like:
[https://www.mikroe.com/m-bus-master-click](https://www.mikroe.com/m-bus-master-click)

**Comment by FKW9** [comment]
As far as I know, the smartmeter acts as a master. It sends data every 5 seconds and, to my knowledge, does not respond to other requests.
I also think I read that smart meters are defined as masters according to some specification, but unfortunately I could not find the source anymore.

**Comment by JohannesKaranitsch** [comment]
Thank you for your fast response!

**Comment by FKW9** [comment]
and yes, the linked converter is right!

**Comment by Noschvie** [comment]
Have a look to https://at.rs-online.com/web/p/entwicklungstools-kommunikation-und-drahtlos/2167484
