### ISSUE TITLE
Setup EVN Key

### ISSUE THREAD

**Issue by wuliwux** [FKW9/esp-smartmeter-netznoe#6]
Hi,

maybe i overread it. but how i setup the EVN Key?
The EVN sends me a Key with a length of 32.

the unsigned char KEY[] in the config.h has a length of 16...

How to Convert the EVN key?

I'm confused...

thanks for help!

greets

**Comment by SebTrax** [comment]
0x and then every time 2 digits of your key.
For Example: 0x22 0x2A 0xEH ...

**Comment by FKW9** [comment]
yes, a key looks like that: 36C66639E48A8CA4D6BC8B282A793BBB
so it is {0x36, 0xC6, 0x66 ...} and so on

**Comment by wuliwux** [comment]
oh, no... so simple... 

warum schreib ich eigentlich in englisch? 
Hier geht es um die EVN... :-)

Vielen dank für die Hilfe!

2 andere fragen hätte ich noch:

- muss der Smart Meter laut evn portal bereits auf kommunikativ sein damit die Kommunikation mit mod-bus funktioniert?
- Hat jemand eine mqtt version auch schon zusammengebastelt?

vielen dank und 
liebe grüße

**Comment by SebTrax** [comment]
:D ja so viele werden das ned auf Englisch brauchen :D hab eh überlegt ob ich Deutsch oder Englisch schreiben soll.

Ich glaub bei dem Kommunikativ gehts nur um die Cloud, dass du dir das online ansehen kannst.

Ich habs auf Modbus umgeschrieben.
Kannst gerne haben wennst willst, ich muss aber noch meinen Key und meine Netzwerkzugangsdaten umschreiben.

Irgendwie funktioniert bei mir der Power-Factor nicht. Hab mir das aber noch ned genauer angesehen.
Könntest ja dann mal berichten, ob der bei dir funktioniert.
Ich hab nämlich nicht den Kaifa sondern den Sagemcom T210-D, vielleicht is da irgendwas minimal anders.
Sonst geht alles, läuft aber erst 2 Tage bei mir.

**Comment by FKW9** [comment]
Modbus wäre mir neu ... ihr meint wohl Meter Bus? ;)
Die "Original" Version von DomiStyle [esphome-dlms-meter](https://github.com/DomiStyle/esphome-dlms-meter) unterstützt denke ich MQTT, hab darin aber keine Erfahrung.

**Comment by SebTrax** [comment]
Ah sorry... ich meinte, dass ich es auf MQTT umgeschrieben hab, ned auf Modbus :D

**Comment by wuliwux** [comment]
@mod-bus vs meter-bus...
yes, das ist wohl richtig. :D

@mqtt? 
aber hallo, ja bitte...
:-)

lg

**Comment by SebTrax** [comment]
@wuliwux ich hoffe man darf das hier so anhängen.
Die [https://github.com/Mbed-TLS/mbedtls.git](url) musst du noch herunterladen, im Script musst du aber noch das "include" der mbedtls ändern, da ich die lib direkt im Projektordner abgelegt habe.
[EVN_SmartMeter_MQTT.zip](https://github.com/FKW9/esp-smartmeter-netznoe/files/9581786/EVN_SmartMeter_MQTT.zip)

**Comment by wuliwux** [comment]
servus, 
erstmal vielen dank für die tollen Inputs.
Hab mal FKW9 Version auf mqtt umgebaut und ein wenig refactoring betrieben.

die daten laufen bei mir jetzt mittels mqtt auf iobroker, richtig nette sache... :-)

lg

**Comment by SebTrax** [comment]
@wuliwux 
Welchen Stromzähler hast du? Kaifa oder Sagemcom?
Bekommst du den PowerFaktor?

**Comment by wuliwux** [comment]
den kaifa.

Was meinst du mit PowerFaktor?
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1975703/190724351-e884613c-0337-489d-ba59-d343a20a54c8.png">


das kennst du bestimmt schon:
https://www.michaelreitbauer.at/sagemcom-t210-d-auslesen-smart-meter-evn/

**Comment by SebTrax** [comment]
Den cosphi meinte ich.
Ja das Projekt kenn ich, ist aber leider in Python.
Bin im programmieren ned unbedingt Weltmeister sondern eher Hobbybastler mit viel Strg-C Strg-V und viel Hoffnung, dass es funktioniert wie ich das will :D

Sonst bekomm ich eh alle Werte, nur den cosphi nicht, muss ich mir bei gelegenheit mal ansehn warum das so ist. Ich vermute, dass der Kaifa da was anderes ausgibt als der Sagemcom.
