### ISSUE TITLE
Sagemcom T210-D how to fix Power-Factor (cosphi) not working

### ISSUE THREAD

**Issue by SebTrax** [FKW9/esp-smartmeter-netznoe#7]
Hallo,
Der Code funktioniert auch beim Sagemcom T210-D, nur der Power-Factor geht nicht.
Fehlerbehebung:
Der "obis_data_type" vom Power-Factor ist nicht 0x12 sondern 0x10
Ich habe in main.cpp "case DATA_LONG_UNSIGNED2:" hinzugefügt
und im obis.h "#define DATA_LONG_UNSIGNED2 0x10".
Siehe Screenshots:
![main-cpp](https://user-images.githubusercontent.com/81617786/190992549-34a3f5c9-11c4-458c-86e5-924a2b8e2ed1.PNG)
![obis-h](https://user-images.githubusercontent.com/81617786/190992553-fba9726d-4189-47ef-b6cd-82bc748e4e7f.PNG)

**Comment by FKW9** [comment]
Danke, habs comitted...
...hab vielleicht etwas vorschnell comitted: gibt der Sagecom überhaupt den Leistungsfaktor aus? Hab dazu keine Informationen gefunden!
Kannst du es vielleicht bestätigen? Einmal ohmsche Lasten (alles was heizt) im Netz betreiben, dann kapazitive/induktive Lasten (Drehstrommotoren) und schauen ob der cos(phi) plausibel ausschaut. Falls du die Möglichkeiten/Lust hast natürlich.

**Comment by SebTrax** [comment]
Was ich bis jetzt gesehen habe, zeigt er da tatsächlich nicht das richtige an.
Ich hab mal die EVN angeschrieben, was da los ist, weil in der Anleitung steht er ja drin.
Ich hab mal so um die 3,5kW von 4kW Gesamt mit Motoren verbraucht und der cos(phi) war bei 0,94-0,98 also eher unglaubwürdig.
Es passt auch rechnerisch ned zusammen, wenn ich die Gesamtleistung aus den Spannungen und Strömen mit dem cos(phi) berechne und mit der Gesamtleistung vom Smartmeter vergleiche.

Ich werd das mal die nächsten Tage verfolgen und wenn nicht, muss ich den cos(phi) wieder rechnen.

Funktioniert beim Kaifa der cos(phi)?
Könntest du mir mal eine entschlüsselte Ausgabe vom Kaifa schickn?

**Comment by FKW9** [comment]
cos(phi) funktioniert beim Kaifa und wird auch so explizit angegeben. Werte sind auch realistisch und passen mit der Blindleistung zusammen. Schau mal hier [AuswertungDLMS_ADPU.xlsx](https://github.com/FKW9/esp-smartmeter-netznoe/blob/b0da1e34e10639d481323ae69186ec9f7853c321/data/AuswertungDLMS_ADPU.xlsx), da ist eine entschlüsselte Nachricht. 
Hab remote kein Zugriff auf die Daten.. kann ich der erst am Wochenende mehr erzählen

**Comment by FKW9** [comment]
Hier mal mein cos(phi) während ein 6kW Motor arbeitet ;)
![chrome_2022-09-24_19-47-10](https://user-images.githubusercontent.com/89307932/192111806-d5e41a1b-c212-448e-a377-31279be0b56c.png)

**Comment by SebTrax** [comment]
Naja ein cos(phi) von 0,45 kann ja auch ned wirklich stimmen.
Beim Sagemcom ist der cos(phi) ein signed int und geht in + als auch in - richtung, was eigentlich falsch ist.
Und anscheinend wird der gesamte cos(phi) aus den 3 einzelnen zusammengezählt und da es auch mal möglich ist, dass 2 Phasen vom Netz beziehen und 1 Phase einspeist, kommt da dann noch mehr blödsinn raus.
So zumindest meine Vermutung.
Ich habs der EVN schon geschrieben und warte zurzeit auf eine Antwort. Vielleicht werden die mich eines besseren belehren 😆

Das ist mein cos(phi), hab aber die negativen Werte auf positive umgerechnet.
![Screenshot_20220924-205819_Chrome](https://user-images.githubusercontent.com/81617786/192114343-f9fb173d-5b0a-4ed3-895c-62e6e1cace90.jpg)

**Comment by SebTrax** [comment]
Kurzes Update:
Bei mir wurde wegen dem komischen cos(phi) bei Bezug + Einspeisung jetzt der Zähler auch auf einen KAIFA getauscht.
Die Änderung wie oben bereits beschrieben funktioniert trotzdem beim Sagemcom, sollte jedoch auch eingespeist werden, zeigt der cos(phi) falsche Werte an.

**Comment by Soundrico** [comment]
ein Hällöle ausm Ländle,
habs auch nachgebaut - coole Arbeit, Jungs!
habe einen Honeywell DM515 Zähler der VKW bekommen (Schauen eigendlich alle gleich aus die Dinger)...
...Mbus angesteckt und läuft...
...bis auf den cos phi - habe den code angepasst lt der obrigen beschreibung...
...cos phi wird immer noch nicht korrekt angezeigt
...hat jemand eine Idee?

**Comment by SebTrax** [comment]
Ich hab das Problem noch immer, dass der cos phi durch null geht, wenn auf einer Phase eingespeist und auf einer anderen bezogen wird.
Ist in meinen Augen ein Fehler in den Zählern.
Vermutlich haben die bei Bezug positive Werte und bei Einspeisung negative und zählen die dann eifach zusammen.
