### ISSUE TITLE
[Question] PCB's noch verfügbar ?

### ISSUE THREAD

**Issue by Noschvie** [FKW9/esp-smartmeter-netznoe#9]
Hallo Florian
hättest du noch ein PCB zum Weitergeben ?
mfg
Norbert

**Comment by FKW9** [comment]
Hallo, ja, ist noch verfügbar. Brauchst du nur die PCB?

**Comment by Noschvie** [comment]
Bestückt wäre noch besser

**Comment by FKW9** [comment]
Bestückt und getestet wirds aufjedenfall teurer, weil ich dummerweise keine SMT Schablone habe und die Lötpaste händisch aufbringen muss.

Habe mal die Kosten durchgerechnet (siehe auch in der BOM im Ordner [hardware](https://github.com/FKW9/esp-smartmeter-netznoe/tree/master/hardware)), wenn du alles so ziemlich fertig haben willst.

| **Kostenstelle**                                 | **Preis**     |
|--------------------------------------------------|---------------|
| Mainboard PCB + Bauteile (exkl. M-Bus Konverter) | 18,21€        |
| Display PCB + Bauteile                           | 6,32€         |
| Mikroe M-Bus Konverter (inkl. Versand)           | 32,00€        |
| Bestücken und Löten (ca. 2h) + E-Test            | 70,00€        |
| Kabel + RJ12 Adapter                             | 3,00€         |
| Versand ca. (innerhalb Österreich)               | 6,90€         |
| **_GESAMT_**                                     | **_136,43€_** |

Muss morgen schauen, ob ich noch ein Gehäuse habe ([Hier der Link](https://at.rs-online.com/web/p/universalgehause/3822106?redirect-relevancy-data=7365617263685F636173636164655F6F726465723D31267365617263685F696E746572666163655F6E616D653D4931384E53656172636847656E65726963267365617263685F6D617463685F6D6F64653D6D61746368616C6C7061727469616C267365617263685F7061747465726E5F6D6174636865643D5E5B5C707B4C7D5C707B4E647D2D2C2F255C2E5D2B24267365617263685F747970653D4B4559574F52445F53494E474C455F414C5048415F4E554D45524943267365617263685F7370656C6C5F636F72726563745F6170706C6965643D59267365617263685F77696C645F63617264696E675F6D6F64653D4E4F4E45267365617263685F6B6579776F72643D313539314153464C424B267365617263685F6B6579776F72645F6170703D313539314153464C424B26)). Wenn ja, kann ich das noch anbieten (ca. 1h Aufwand).

_Es handelt sich um keinen Endgültigen Preis._

**Comment by Noschvie** [comment]
Suche eine einfachere Lösung, danke nochmals.
